version: '3'
volumes:
  node_modules:
services:
    app:
        container_name: mobi_container
        restart: always
        build: ./
        command: node app.js
        volumes:
          - ./:/usr/src/app/
          - node_modules:/usr/src/app/node_modules
        ports:
          - 3000:3000
        links:
          - mongodb
          # - elastic
    mongodb:
      container_name: mongo_container
      image: mongo:latest
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
#     elastic:
#       container_name: elastic_container
#       image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
#       volumes:
#         - esdata:/usr/share/elasticsearch/data
#       environment:
#         - cluster.name=docker-cluster
#         - bootstrap.memory_lock=true
#         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       ulimits:
#         memlock:
#           soft: -1
#           hard: -1
#       ports:
#         - "9200:9200"
# volumes:
#   esdata:
#     driver: local
